const vuetom = require('./vuetom.min.js')
const help = require('./plugin/help.js')
const date = require('./plugin/date.js')
// require('./locale/zh-cn.js')

console.log(vuetom)
console.log(vuetom().options)
console.log(vuetom().version)
console.log(vuetom.langs)

vuetom.use(help)
vuetom.use(date)
console.log(vuetom().$locale())
console.log(vuetom().help())
console.log(vuetom({ locale: 'zh-cn' }).date(new Date(), 'YYYY-MM-DD HH:mm:ss'))
console.log(vuetom.lang)
